language: node_js
node_js:
  - "8"

before_install:
  - openssl aes-256-cbc -K $encrypted_351e7f410f9a_key -iv $encrypted_351e7f410f9a_iv -in id_travis_rsa.enc -out id_travis_rsa -d
  - chmod 400 id_travis_rsa

after_success:
  - ssh-keyscan -t rsa,dsa,ecdsa -H $DEPLOY_REPO_HOST 2>&1 | tee -a ${TRAVIS_HOME}/.ssh/known_hosts
  - git remote add deploy "$DEPLOY_REPO_USER@$DEPLOY_REPO_HOST:$DEPLOY_REPO_PATH"
  - ssh-agent bash -c 'ssh-add id_travis_rsa; git push deploy master'
